name: Daily DevSync Commit

on:
  # This schedule runs at 8:30 UTC every day.
  # You can change '30 8' to any specific minute and hour.
  schedule:
    - cron: '30 8 * * *'
  
  # This allows you to run the workflow manually
  workflow_dispatch:

jobs:
  daily-commit:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository's code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Configure Git user (includes your email in the name)
      - name: Configure Git user for 24f2002682@ds.study.iitm.ac.in
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'

      # Step 3: Create an empty commit and push it
      - name: Create and push daily commit
        run: |
          git commit --allow-empty -m "Daily automated commit for DevSync"
          git push
